TodoList/Models/TodoDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TodoList.Models
{
    public class TodoDetail
    {
        public int ID { get; set; }

        public string Description { get; set; }

        public bool Isdone { get; set; }

        public virtual ApplicationUser User { get; set; }

        public bool IsParent { get; set; }

        public int ParentID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DeadlineDate { get; set; }

    }
}

TodoList/Controllers/TodoDetailsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TodoList.Models;

namespace TodoList.Controllers
{
    public class TodoDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TodoDetails
        public ActionResult Index()
        {
            //this will get us the current user
            //string currentUserId = User.Identity.GetUserId();
            //ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);//looking into db
            return View();// db.todoDetails.ToList().Where(x=>x.User==currentUser));
        }

        private IEnumerable<TodoDetail> getMytodos()
        {
             string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);//looking into db
            IEnumerable<TodoDetail> mytodo = db.todoDetails.ToList().Where(x => x.User == currentUser && x.IsParent);
            //for complete percentage
            //int count = 0;
            //foreach(TodoDetail todoDetail in mytodo)
            //{
            //    count++;
            //}
            return mytodo;
        }
        private List<TodoList.Models.TodoDetail> GetNewMyTodos()
        {

            var child = (List<TodoList.Models.TodoDetail>)getMytodosChild().ToList();
            var parent = (List<TodoList.Models.TodoDetail>)getMytodos().ToList();
            List<TodoList.Models.TodoDetail> todo = new List<TodoDetail>();
            foreach (var item in parent)
            {
                todo.Add(item);
                var result = child.Where(ch => ch.ParentID == item.ID).ToList();
                foreach (var ch in result)
                {
                    todo.Add(ch);
                }
            }
            return todo;
        }
        private IEnumerable<TodoDetail> getMytodosChild()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);//looking into db
            IEnumerable<TodoDetail> mytodo = db.todoDetails.ToList().Where(x => x.User == currentUser && !x.IsParent);

            return mytodo;
        }

        public ActionResult tabView()
        {
            //this will get us the current user

            //string currentUserId = User.Identity.GetUserId();
            //ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);//looking into db
            //getting the list of todos for the user that is currently logged in the application

            //return PartialView("_tabView", getMytodos());//,db.todoDetails.ToList().Where(x => x.User == currentUser));
            return PartialView("_tabView", GetNewMyTodos());//,db.todoDetails.ToList().Where(x => x.User == currentUser));
        }


        public ActionResult allTodos()
        {
            return View(db.todoDetails.ToList());
        }

        // GET: TodoDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoDetail todoDetail = db.todoDetails.Find(id);
            if (todoDetail == null)
            {
                return HttpNotFound();
            }
            return View(todoDetail);
        }

        // GET: TodoDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateChild(int id)
        {
            ViewBag.ParentId = id;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateChild([Bind(Include = "ID,Description,DeadlineDate,Isdone")] TodoDetail todoDetail)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                todoDetail.User = currentUser;
                todoDetail.IsParent = false;
                todoDetail.ParentID = todoDetail.ID;
                todoDetail.ID = 0;

                db.todoDetails.Add(todoDetail);
                db.SaveChanges();
              return RedirectToAction("Index");
            }

            return View(todoDetail);
        }
        //public ActionResult CreateChild(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TodoDetail todoDetail = db.todoDetails.Find(id);
        //    if (todoDetail == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View();
        //}

        // POST: TodoDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,DeadlineDate")] TodoDetail todoDetail)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x=>x.Id==currentUserId);
                todoDetail.User = currentUser;
                todoDetail.IsParent = true;
                todoDetail.ParentID = 0;

                db.todoDetails.Add(todoDetail);
                db.SaveChanges();
               return RedirectToAction("Index");
            }

            //return View(todoDetail);
            return PartialView("_tabView", GetNewMyTodos());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxCreate([Bind(Include = "ID,Description,DeadlineDate")] TodoDetail todoDetail)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                todoDetail.User = currentUser;
                todoDetail.Isdone = false;//because we have just created

                db.todoDetails.Add(todoDetail);
                db.SaveChanges();
                //return RedirectToAction("Index"); //no need to redirect but we will return the partial view
                
            }

            //return PartialView("_tabView", getMytodos());
            return PartialView("_tabView", GetNewMyTodos());
        }

        // GET: TodoDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoDetail todoDetail = db.todoDetails.Find(id);
            if (todoDetail == null)
            {
                return HttpNotFound();
            }

            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);//looking into db
            
            if(todoDetail.User!=currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(todoDetail);
        }

        // POST: TodoDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for runs when we click save
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,DeadlineDate,Isdone")] TodoDetail todoDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(todoDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return PartialView("_tabView", GetNewMyTodos());
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult AjaxEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoDetail todoDetail = db.todoDetails.Find(id);
            if (todoDetail == null)
            {
                return HttpNotFound();
            }
            else
            {
                todoDetail.Isdone = value;
                db.Entry(todoDetail).State = EntityState.Modified; //looks the todo and modifies the changes
                db.SaveChanges();
                //return PartialView("_tabView", getMytodos());
                return PartialView("_tabView", GetNewMyTodos());
            }

            //if (ModelState.IsValid)
            //{
            //    db.Entry(todoDetail).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //return View(todoDetail);
        }

        // GET: TodoDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoDetail todoDetail = db.todoDetails.Find(id);
            if (todoDetail == null)
            {
                return HttpNotFound();
            }
            return View(todoDetail);
        }

        // POST: TodoDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

TodoList/Views/TodoDetails/Create.cshtml
@model TodoList.Models.TodoDetail

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TodoDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeadlineDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeadlineDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeadlineDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    @*@Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

        <script type="text/javascript">
            $(document).ready(function () {
                $('input[type=datetime]').datepicker({
                    dateFormat: "dd/M/yy",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0"
                });

            });
        </script>*@

}

TodoList/Views/TodoDetails/CreateChild.cshtml
@model TodoList.Models.TodoDetail

@{
    ViewBag.Title = "CreateChilds";
}

<h2>CreateChild</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TodoDetail</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeadlineDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeadlineDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeadlineDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Isdone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Isdone)
                    @Html.ValidationMessageFor(model => model.Isdone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @*@Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>*@

}

TodoList/Views/TodoDetails/Delete.cshtml
@model TodoList.Models.TodoDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeadlineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeadlineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Isdone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isdone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TodoList/Views/TodoDetails/Details.cshtml
@model TodoList.Models.TodoDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TodoDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeadlineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeadlineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Isdone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isdone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TodoList/Views/TodoDetails/Edit.cshtml
@model TodoList.Models.TodoDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TodoDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeadlineDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeadlineDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeadlineDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Isdone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Isdone)
                    @Html.ValidationMessageFor(model => model.Isdone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    @*@Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>*@

}

TodoList/Views/TodoDetails/Index.cshtml
@model TodoList.Models.TodoDetail
<!--this particular views expects the todolists-->

@{
    /**/

    ViewBag.Title = "Index";
}


@*removing the following code and building ajax call to create the form*@

@*<h2>Index</h2>
    <p>@Html.ActionLink("Create New", "Create")</p>*@

@*using ajax helper to create todo form*@

<div id="tabView"></div>

<div id="todoCreate">
    @using (Ajax.BeginForm("AjaxCreate", "TodoDetails", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tabView"
    }))
    {
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="create" value="Create New Todo" class="btn btn-default" onclick="location.href='TodoDetails/Create';" />
        </div>
    </div>
    }
</div>
@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts_Customized/tabJS.js"></script>

    @* <!--this will load client side validation--> *@
    @Scripts.Render("~/bundles/jqueryval")
}

TodoList/Views/TodoDetails/_tabView.cshtml
@model IEnumerable<TodoList.Models.TodoDetail>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Description)*@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Isdone)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @if (!item.IsParent)
            {
                <td></td>
            }
            @*<td id="Description_@item.ID" class="Description_@item.ParentID" >*@
            <td>
                @if (!item.Isdone)
                {
                    if (item.DeadlineDate > DateTime.Now)
                    {
                        @Html.DisplayFor(modelItem => item.Description)
                    }
                    else
                    {
                        <span style="background-color: #ff0000">@Html.DisplayFor(modelItem => item.Description)</span>
                    }
                }
                else
                {
                    <span style="background-color: #FFFF00">@Html.DisplayFor(modelItem => item.Description)</span>
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DeadlineDate)
            </td>


            @*<td id="Isdone_@item.ID" class="Isdone_@item.ParentID">*@
            <td>
                @Html.CheckBoxFor(modelItem => item.Isdone, new { id = item.ID, @class = "ActiveCheck " + item.ParentID })
                @*//so whenever this item will be made, an id will be assigned to that item because id is primary key
                    //classname is given to identify the element*@
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                @if (item.IsParent)
                {
                    @Html.ActionLink("| Create SUB", "CreateChild", new { id = item.ID })
                }
            </td>
        </tr>
    }

</table>

<script src="~/Scripts_Customized/checkboxJS.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
<!-- Required jQuery and jQuery UI Javascript references -->
<!--this js is added to the pv because we want this event listeners to be added anytime this table is created-->
<!--if this is place in index.cshtml then it will only run the first time the page loads-->